import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from './components/Header'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
  className="bg-[#8f5d2b] text-white" 
  style={{ 
    background: 'url(https://img.freepik.com/free-photo/abstract-smooth-brown-wall-background-layout-design-web-template-business-report-with-smooth-circle-gradient-color_1258-54599.jpg)', 
    backgroundSize: 'cover', 
    backgroundRepeat: 'no-repeat' 
  }}
>

          <Header/>
        <main>{children}</main>
        
      </body>
    </html>
  );
}
